name: Run JMeter Tests and Publish Report

on:
  schedule:
    - cron: '0 2 * * *'  # Every day at 2:00 AM UTC (10:00 PM ET)
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  jmeter-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Java 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Install tools and JMeter
      run: |
        sudo apt-get update
        sudo apt-get install -y libxml2-utils curl
        wget https://dlcdn.apache.org//jmeter/binaries/apache-jmeter-5.6.3.tgz
        tar -xzf apache-jmeter-5.6.3.tgz
        echo "$PWD/apache-jmeter-5.6.3/bin" >> $GITHUB_PATH

    - name: Run JMeter test and generate HTML report
      run: |
        mkdir -p results/report
        jmeter -Jxstream.disable=true -n -t tests/APIs_Script.jmx -l results/result.jtl -e -o results/report

    - name: Extract test config from .jmx
      id: jmeter_config
      run: |
        THREADS=$(xmllint --xpath "string(//ThreadGroup/intProp[@name='ThreadGroup.num_threads'])" tests/APIs_Script.jmx 2>/dev/null || echo "Not found")
        RAMPUP=$(xmllint --xpath "string(//ThreadGroup/intProp[@name='ThreadGroup.ramp_time'])" tests/APIs_Script.jmx 2>/dev/null || echo "Not found")
        DURATION=$(xmllint --xpath "string(//ThreadGroup/stringProp[@name='ThreadGroup.duration'])" tests/APIs_Script.jmx 2>/dev/null || echo "Not specified")
        echo "threads=$THREADS" >> $GITHUB_OUTPUT
        echo "rampup=$RAMPUP" >> $GITHUB_OUTPUT
        echo "duration=$DURATION" >> $GITHUB_OUTPUT

    - name: Analyze results and notify Slack
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      run: |
        if [ -z "$SLACK_WEBHOOK" ]; then
          echo "❌ SLACK_WEBHOOK is not set."
          exit 1
        fi

        ERRORS=""
        SLOW=""
        while IFS=',' read -r _ elapsed label code message _ _ _ _ _ _ _ _ url; do
          path=$(echo "$url" | sed -E 's|https?://[^/]+||')
          if [[ $code -ge 500 ]]; then
            ERRORS+="${label} (${path}) → *${code}* (${message}) in ${elapsed}ms 🚨\n"
          elif [[ $code -ge 400 ]]; then
            ERRORS+="${label} (${path}) → ${code} (${message}) in ${elapsed}ms ⚠️\n"
          elif [[ $elapsed -gt 500 ]]; then
            SLOW+="${label} (${path}) → ${elapsed}ms 🐌\n"
          fi
        done < <(tail -n +2 results/result.jtl | awk -F',' '{print $1","$2","$3","$4","$5","$6","$7","$8","$9","$10","$11","$12","$13}')

        MSG=""
        if [ -n "$ERRORS" ]; then
          MSG+="*❌ The following APIs had issues:*\n\n\`\`\`\n$ERRORS\n\`\`\`\n"
        fi
        if [ -n "$SLOW" ]; then
          MSG+="*⏱️ Slow APIs (>500ms):*\n\n\`\`\`\n$SLOW\n\`\`\`\n"
        fi

        if [ -n "$MSG" ]; then
          curl -X POST -H 'Content-type: application/json' --data "{
            \"text\": \"🚨 *JMeter Alert*\\n\\n$MSG\\n*Test Configuration:*\\n• Users: ${{ steps.jmeter_config.outputs.threads }}\\n• Ramp-up: ${{ steps.jmeter_config.outputs.rampup }}s\\n• Duration: ${{ steps.jmeter_config.outputs.duration }}\\n\\n:mag: View report: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/\"
          }" $SLACK_WEBHOOK
        fi

    - name: Deploy HTML report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./results/report
        publish_branch: gh-pages
        force_orphan: true
        keep_files: false
        commit_message: "Deploy JMeter HTML report 🚀"
