name: Run JMeter Tests and Publish Report

on:
  schedule:
    - cron: '0 2 * * *'  # Every day at 2:00 AM UTC (10:00 PM ET)
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  jmeter-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Java 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Install tools and JMeter
      run: |
        sudo apt-get update
        sudo apt-get install -y libxml2-utils curl
        wget https://dlcdn.apache.org//jmeter/binaries/apache-jmeter-5.6.3.tgz
        tar -xzf apache-jmeter-5.6.3.tgz
        echo "$PWD/apache-jmeter-5.6.3/bin" >> $GITHUB_PATH

    - name: Run JMeter test and generate HTML report
      run: |
        mkdir -p results/report
        jmeter -Jxstream.disable=true -n -t tests/APIs_Script.jmx -l results/result.jtl -e -o results/report

    - name: Extract test config from .jmx
      id: jmeter_config
      run: |
        THREADS=$(xmllint --xpath "string(//ThreadGroup/intProp[@name='ThreadGroup.num_threads'])" tests/APIs_Script.jmx 2>/dev/null || echo "Not found")
        RAMPUP=$(xmllint --xpath "string(//ThreadGroup/intProp[@name='ThreadGroup.ramp_time'])" tests/APIs_Script.jmx 2>/dev/null || echo "Not found")
        DURATION=$(xmllint --xpath "string(//ThreadGroup/stringProp[@name='ThreadGroup.duration'])" tests/APIs_Script.jmx 2>/dev/null || echo "Not specified")
        echo "threads=$THREADS" >> $GITHUB_OUTPUT
        echo "rampup=$RAMPUP" >> $GITHUB_OUTPUT
        echo "duration=$DURATION" >> $GITHUB_OUTPUT

    - name: Analyze results and notify Slack
      env:
        SLACK
