name: Run JMeter Tests

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  jmeter-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Instalar JMeter
      run: |
        sudo apt-get update
        sudo apt-get install -y jmeter

    - name: Ejecutar prueba de JMeter y generar .jtl
      run: |
        mkdir -p results/report
        echo "Ejecutando APIs_Script.jmx..."
        jmeter -n -t tests/APIs_Script.jmx -l results/result.jtl -e -o results/report

    - name: Mostrar primeras 20 líneas del .jtl
      run: |
        echo "Mostrando resultado del archivo .jtl:"
        head -n 100 results/result.jtl

